// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ldd27/go-starter-kit/internal/dao"
	"github.com/ldd27/go-starter-kit/internal/router/api/v1"
	"github.com/ldd27/go-starter-kit/internal/service"
	"github.com/ldd27/go-starter-kit/internal/setup/g"
)

// Injectors from wire.go:

func NewExampleController() *v1.ExampleController {
	db := g.DB()
	daoT := dao.NewExampleDao(db)
	exampleSvc := service.NewExampleSvc(daoT)
	exampleController := v1.NewExampleController(exampleSvc)
	return exampleController
}
